"""Cutlery Remote custom-node entry point for ComfyUI."""

from .nodes_remote import (
    NODE_CLASS_MAPPINGS as REMOTE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as REMOTE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .nodes_remote_clip import (
    NODE_CLASS_MAPPINGS as REMOTE_CLIP_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as REMOTE_CLIP_NODE_DISPLAY_NAME_MAPPINGS,
)
from .nodes_remote_proxy import (
    NODE_CLASS_MAPPINGS as REMOTE_PROXY_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as REMOTE_PROXY_NODE_DISPLAY_NAME_MAPPINGS,
)
from .nodes_wf3_boundary import (
    NODE_CLASS_MAPPINGS as WF3_BOUNDARY_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as WF3_BOUNDARY_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **REMOTE_NODE_CLASS_MAPPINGS,
    **REMOTE_CLIP_NODE_CLASS_MAPPINGS,
    **REMOTE_PROXY_NODE_CLASS_MAPPINGS,
    **WF3_BOUNDARY_NODE_CLASS_MAPPINGS,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **REMOTE_NODE_DISPLAY_NAME_MAPPINGS,
    **REMOTE_CLIP_NODE_DISPLAY_NAME_MAPPINGS,
    **REMOTE_PROXY_NODE_DISPLAY_NAME_MAPPINGS,
    **WF3_BOUNDARY_NODE_DISPLAY_NAME_MAPPINGS,
}
WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
